Otat 1238
Flickit-Platform-Dev/flickit-platform pull request #58
Opened 2024-05-20 10:07 UTC by mostafagit

2024-05-20 20:15 UTC, mahdasjs requested changes

2024-05-20 20:15 UTC, mahdasjs commented on frontend/src/components/questions/QuestionCard.tsx
<img width="1440" alt="Screenshot 1403-02-31 at 23 32 27" src="https://github.com/Flickit-Platform-Dev/flickit-platform/assets/45814320/22570b4f-7928-4a06-99c6-af37c93da2bf">
<img width="1440" alt="Screenshot 1403-02-31 at 23 24 43" src="https://github.com/Flickit-Platform-Dev/flickit-platform/assets/45814320/ee978a0a-5c24-4d55-b772-e9453dfe089c">
<img width="1241" alt="Screenshot 1403-02-31 at 23 30 08" src="https://github.com/Flickit-Platform-Dev/flickit-platform/assets/45814320/0b8d9935-50ed-41fe-9d18-9999fac6ac73">

2024-05-20 20:15 UTC, mahdasjs commented on frontend/src/components/questions/QuestionCard.tsx
به نظرم یکی از این سه حالت برای استایل ایکون‌های دیلیت و ادیت اعمال بشه خیلی خوب میشه یا هر دوشون کنار هم توی باکس کامنت قرار بگیرن که من خودم اینو بیشتر دوست دارم  یا مثل حالت دوم یا سوم باشه به نظرم اگرم مثل حالتی که خودتون زدید. میخواید باشه به نظرم بهتره که باکس یک خطی هم اندازش  برابر با باکس‌های دوخطی بشه

2024-05-20 20:15 UTC, mahdasjs commented on frontend/src/components/questions/QuestionCard.tsx
> +                      <Box
به نظرم کل این باکس مربوط به دایلوگ توی فانکشن جدید توی همین کامپوننت تعریف بشه و ازش استفاده بشه

2024-05-20 20:15 UTC, mahdasjs commented on frontend/src/components/questions/QuestionCard.tsx
> +                      >
<img width="1440" alt="image" src="https://github.com/Flickit-Platform-Dev/flickit-platform/assets/45814320/1de6aea3-0b58-4360-84e6-f871c44f8eb9">

در حالت ریسپانسیو به صورت تمام صفحه دایلوگ رو نشون میده که به نظرم خوب نیست و به نظرم بهتره کاربر بتونه بقیه صفحه رو ببینه
بهتره به دایلوگ هدر و علامت ضربدر در بالا سمت راست اضافه بشه

2024-05-21 09:28 UTC, mostafagit commented on frontend/src/components/questions/QuestionCard.tsx
مورد دوم رو لحاظ کردم

2024-05-21 09:29 UTC, mostafagit commented on frontend/src/components/questions/QuestionCard.tsx
> +                      <Box
کامپوننت ساخته شد.

2024-05-26 06:43 UTC, amirrezaflh1402 commented
مودال حذف تو حالت موبایل طبق طراحی نیست

2024-05-26 06:44 UTC, amirrezaflh1402 commented
اگه فارسی تایپ کنیم input بهم میریزه

2024-05-26 15:14 UTC, mostafagit commented
> مودال حذف تو حالت موبایل طبق طراحی نیست

done.

2024-05-26 15:14 UTC, mostafagit commented
> ف تو حالت موبایل

میشه یه عکس ارسال کنید. متوجه نشدم.

2024-05-26 16:15 UTC, mahdasjs approved these changes

2024-05-27 13:25 UTC, mostafagit commented
> > ف تو حالت موبایل
> 
> میشه یه عکس ارسال کنید. متوجه نشدم.

done

2024-05-28 05:55 UTC, amirrezaflh1402 approved these changes

2024-05-28 05:56 UTC, merged